version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build s3://test-code-pipe-line/ --delete
      - aws cloudfront create-invalidation --distribution-id E1KEXHGIXDGA9D --paths "/*"
artifacts:
  files:
    - 'build/*'
    - 'build/**/*'